---
title: "Emily Bay Chi squared/Fisher's exact test"
format: html
---

```{r}
library(ggplot2)
library(tidyr)
```

```{r}
EBRT <- data.frame(
  "RT" = c(15.75, 1.25),
  "Not_RT" = c(18.25, 54.75),
  row.names = c("April", "December"),
  stringsAsFactors = FALSE
)
colnames(EBRT) <- c("RT", "Not_RT")

EBRT

EBDict <- data.frame(
  "Dictyota" = c(3.75, 13),
  "Not_Dictyota" = c(30.25, 43),
  row.names = c("April", "December")
)


EBBT <- data.frame(
  "Lyngbya" = c(0, 6.5),
  "Not Lyngbya" = c(34, 49.5),
  row.names = c("April", "December")
)


EBC <- data.frame(
  "Coral" = c(11, 10.25),
  "Not_Coral" = c(23, 45.75),
  row.names = c("April", "December")
)


EBCaulerpa <- data.frame(
  "Caulerpa" = c(0, 5),
  "Not Caulerpa" = c(34, 51),
  row.names = c("April", "December")
)
```

```{r}
mosaicplot(EBRT,
  main = "Mosaic plot",
  color = TRUE
)
```

```{r}
chisq.test(EBRT)$expected
EBRTChi <- chisq.test(EBRT)
EBRTChi
#X-squared = 24.043, df = 1, p-value = 9.42e-07
#Significant

chisq.test(EBDict)$expected
EBDictChi <- chisq.test(EBDict)
EBDictChi
#X-squared = 1.3472, df = 1, p-value = 0.2458
#No significance

chisq.test(EBBT)$expected
#Cannot use chi squared test
EBBTfish <- fisher.test(EBBT)
EBBTfish
# p-value = 0.07934
# No significance

chisq.test(EBC)$expected
EBCChi <- chisq.test(EBC)
EBCChi
#X-squared = 1.6018, df = 1, p-value = 0.2057
#No significance

chisq.test(EBCaulerpa)$expected
EBCaulerpaChi <- chisq.test(EBCaulerpa)
EBCaulerpaChi
#X-squared = 1.7378, df = 1, p-value = 0.1874
#No Significance
```

Multiple test P-value adjustment Bonferroni
```{r}
p = c(9.42e-07, 0.2458, 0.07934, 0.2057, 0.1874)
adjp <- p.adjust(p, method = "bonferroni", n = length(p))
adjp
# 4.710e-06 1.000e+00 3.967e-01 1.000e+00 9.370e-01
```